FROM openjdk:17-oracle
MAINTAINER bkazazic
COPY build/libs/aggregator-microservice-0.0.1-SNAPSHOT.jar aggregator-microservice-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/aggregator-microservice-0.0.1-SNAPSHOT.jar"]