version: 2.15.0
services:
  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - spring-cloud-network

  config-server:
    build:
      context: config-server-microservice
      dockerfile: Dockerfile
    image: config-server-microservice:latest
    networks:
      - spring-cloud-network

  eureka-server:
    build:
      context: eureka-server
      dockerfile: Dockerfile
    image: eureka-server:latest
    ports:
      - "8761:8761"
    networks:
      - spring-cloud-network

networks:
    spring-cloud-network:
      driver: bridge