FROM openjdk:17-oracle
MAINTAINER bkazazic
COPY build/libs/temperature-microservice-0.0.1-SNAPSHOT.jar temperature-microservice-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/temperature-microservice-0.0.1-SNAPSHOT.jar"]