FROM openjdk:17-oracle
MAINTAINER bkazazic
COPY build/libs/humidity-microservice-0.0.1-SNAPSHOT.jar humidity-microservice-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/humidity-microservice-0.0.1-SNAPSHOT.jar"]