FROM openjdk:17-oracle
MAINTAINER bkazazic
COPY build/libs/config-server-microservice-0.0.1-SNAPSHOT.jar config-server-microservice-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java", "-jar", "/config-server-microservice-0.0.1-SNAPSHOT.jar"]
